/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as ContactusImport } from './routes/contactus'
import { Route as LayoutPrivateImport } from './routes/_layout-private'
import { Route as Import } from './routes/*'
import { Route as LayoutPrivatePostsIndexImport } from './routes/_layout-private/posts/index'
import { Route as LayoutPrivateDashboardIndexImport } from './routes/_layout-private/dashboard/index'
import { Route as LayoutPrivateAccountIndexImport } from './routes/_layout-private/account/index'
import { Route as LayoutPrivatePostsPostIdImport } from './routes/_layout-private/posts/$postId'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const ContactusRoute = ContactusImport.update({
  path: '/contactus',
  getParentRoute: () => rootRoute,
} as any)

const LayoutPrivateRoute = LayoutPrivateImport.update({
  id: '/_layout-private',
  getParentRoute: () => rootRoute,
} as any)

const Route = Import.update({
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutPrivatePostsIndexRoute = LayoutPrivatePostsIndexImport.update({
  path: '/posts/',
  getParentRoute: () => LayoutPrivateRoute,
} as any)

const LayoutPrivateDashboardIndexRoute =
  LayoutPrivateDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => LayoutPrivateRoute,
  } as any)

const LayoutPrivateAccountIndexRoute = LayoutPrivateAccountIndexImport.update({
  path: '/account/',
  getParentRoute: () => LayoutPrivateRoute,
} as any)

const LayoutPrivatePostsPostIdRoute = LayoutPrivatePostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => LayoutPrivateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/*': {
      id: '/*'
      path: '/*'
      fullPath: '/*'
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_layout-private': {
      id: '/_layout-private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutPrivateImport
      parentRoute: typeof rootRoute
    }
    '/contactus': {
      id: '/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout-private/posts/$postId': {
      id: '/_layout-private/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPrivatePostsPostIdImport
      parentRoute: typeof LayoutPrivateImport
    }
    '/_layout-private/account/': {
      id: '/_layout-private/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutPrivateAccountIndexImport
      parentRoute: typeof LayoutPrivateImport
    }
    '/_layout-private/dashboard/': {
      id: '/_layout-private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutPrivateDashboardIndexImport
      parentRoute: typeof LayoutPrivateImport
    }
    '/_layout-private/posts/': {
      id: '/_layout-private/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPrivatePostsIndexImport
      parentRoute: typeof LayoutPrivateImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  Route,
  LayoutPrivateRoute: LayoutPrivateRoute.addChildren({
    LayoutPrivatePostsPostIdRoute,
    LayoutPrivateAccountIndexRoute,
    LayoutPrivateDashboardIndexRoute,
    LayoutPrivatePostsIndexRoute,
  }),
  ContactusRoute,
  SearchRoute,
  AboutLazyRoute,
  LoginLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/*",
        "/_layout-private",
        "/contactus",
        "/search",
        "/about",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/*": {
      "filePath": "*.tsx"
    },
    "/_layout-private": {
      "filePath": "_layout-private.tsx",
      "children": [
        "/_layout-private/posts/$postId",
        "/_layout-private/account/",
        "/_layout-private/dashboard/",
        "/_layout-private/posts/"
      ]
    },
    "/contactus": {
      "filePath": "contactus.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_layout-private/posts/$postId": {
      "filePath": "_layout-private/posts/$postId.tsx",
      "parent": "/_layout-private"
    },
    "/_layout-private/account/": {
      "filePath": "_layout-private/account/index.tsx",
      "parent": "/_layout-private"
    },
    "/_layout-private/dashboard/": {
      "filePath": "_layout-private/dashboard/index.tsx",
      "parent": "/_layout-private"
    },
    "/_layout-private/posts/": {
      "filePath": "_layout-private/posts/index.tsx",
      "parent": "/_layout-private"
    }
  }
}
ROUTE_MANIFEST_END */
